/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string>;

export interface Users {
  birthdate: Timestamp;
  created_at: Timestamp;
  email: string;
  first_name: string;
  id: Generated<number>;
  last_name: string;
  password: string;
  updated_at: Timestamp;
}

export interface DB {
  users: Users;
}
