volumes:
  pgdata:

services:
  postgres:
    image: postgres:17-bookworm
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: chronocademy
      POSTGRES_USER: chronocademy
      POSTGRES_PASSWORD: chronocademy
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    depends_on:
      postgres:
          condition: service_healthy
    build:
      context: .
      target: dev
    expose:
        - 3000
    volumes:
      - .:/app
    ports:
      - 3000:3000
