import { DB } from "@/app/database";
import type { Kysely } from "kysely";

export async function seed(db: Kysely<DB>): Promise<void> {
  const mapLanguagesToValues = (languages: string[]) => {
    return languages.map((language) => ({ language }));
  };

  await db.deleteFrom("languages").execute();

  await db
    .insertInto("languages")
    .values(
      mapLanguagesToValues([
        "Afar",
        "Abkhaz",
        "Avestan",
        "Afrikaans",
        "Akan",
        "Amharic",
        "Aragonese",
        "Arabic",
        "Assamese",
        "Avaric",
        "Aymara",
        "Azerbaijani",
        "South Azerbaijani",
        "Bashkir",
        "Belarusian",
        "Bulgarian",
        "Bihari",
        "Bislama",
        "Bambara",
        "Bengali",
        "Tibetan Standard",
        "Breton",
        "Bosnian",
        "Catalan",
        "Chechen",
        "Chamorro",
        "Corsican",
        "Cree",
        "Czech",
        "Old Church Slavonic",
        "Chuvash",
        "Welsh",
        "Danish",
        "German",
        "Divehi",
        "Dzongkha",
        "Ewe",
        "Greek",
        "English",
        "Esperanto",
        "Spanish",
        "Estonian",
        "Basque",
        "Persian (Farsi)",
        "Fula",
        "Finnish",
        "Fijian",
        "Faroese",
        "French",
        "Western Frisian",
        "Irish",
        "Scottish Gaelic",
        "Galician",
        "Guaraní",
        "Gujarati",
        "Manx",
        "Hausa",
        "Hebrew (modern)",
        "Hindi",
        "Hiri Motu",
        "Croatian",
        "Haitian",
        "Hungarian",
        "Armenian",
        "Herero",
        "Interlingua",
        "Indonesian",
        "Interlingue",
        "Igbo",
        "Nuosu",
        "Inupiaq",
        "Ido",
        "Icelandic",
        "Italian",
        "Inuktitut",
        "Japanese",
        "Javanese",
        "Georgian",
        "Kongo",
        "Kikuyu",
        "Kwanyama",
        "Kazakh",
        "Kalaallisut",
        "Khmer",
        "Kannada",
        "Korean",
        "Kanuri",
        "Kashmiri",
        "Kurdish",
        "Komi",
        "Cornish",
        "Kyrgyz",
        "Latin",
        "Luxembourgish",
        "Ganda",
        "Limburgish",
        "Lingala",
        "Lao",
        "Lithuanian",
        "Luba-Katanga",
        "Latvian",
        "Malagasy",
        "Marshallese",
        "Māori",
        "Macedonian",
        "Malayalam",
        "Mongolian",
        "Marathi (Marāṭhī)",
        "Malay",
        "Maltese",
        "Burmese",
        "Nauru",
        "Norwegian Bokmål",
        "North Ndebele",
        "Nepali",
        "Ndonga",
        "Dutch",
        "Norwegian Nynorsk",
        "Norwegian",
        "South Ndebele",
        "Navajo",
        "Chichewa",
        "Occitan",
        "Ojibwe",
        "Oromo",
        "Oriya",
        "Ossetian",
        "Panjabi",
        "Pāli",
        "Polish",
        "Pashto",
        "Portuguese",
        "Quechua",
        "Romansh",
        "Kirundi",
        "Romanian",
        "Russian",
        "Kinyarwanda",
        "Sanskrit (Saṁskṛta)",
        "Sardinian",
        "Sindhi",
        "Northern Sami",
        "Sango",
        "Sinhala",
        "Slovak",
        "Slovene",
        "Samoan",
        "Shona",
        "Somali",
        "Albanian",
        "Serbian",
        "Swati",
        "Southern Sotho",
        "Sundanese",
        "Swedish",
        "Swahili",
        "Tamil",
        "Telugu",
        "Tajik",
        "Thai",
        "Tigrinya",
        "Turkmen",
        "Tagalog",
        "Tswana",
        "Tonga (Tonga Islands)",
        "Turkish",
        "Tsonga",
        "Tatar",
        "Twi",
        "Tahitian",
        "Uyghur",
        "Ukrainian",
        "Urdu",
        "Uzbek",
        "Venda",
        "Vietnamese",
        "Volapük",
        "Walloon",
        "Wolof",
        "Xhosa",
        "Yiddish",
        "Yoruba",
        "Zhuang",
        "Chinese",
        "Zulu",
      ]),
    )
    .execute();
}
