#!/usr/bin/env bash

set -euo pipefail

pg_user=chronocademy
pg_db=chronocademy
schema=$(mktemp)

docker compose exec postgres pg_dump -U "${pg_user}" --schema-only -d "${pg_db}" > "${schema}"

docker compose exec postgres dropdb -U "${pg_user}" "${pg_db}" --force
docker compose exec postgres createdb -U "${pg_user}" "${pg_db}"

docker compose exec postgres psql -U "${pg_user}" -d "${pg_db}" -c "$(cat "${schema}")" >/dev/null
