#!/usr/bin/env bash

set -euo pipefail

dirname=$(dirname "$0")

pg_user=chronocademy
pg_db=chronocademy

source "${dirname}/../.env"

docker compose exec postgres dropdb -U "${pg_user}" "${pg_db}" --force
docker compose exec postgres createdb -U "${pg_user}" "${pg_db}"

kysely migrate:latest
kysely seed:run
